apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeshark
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kubeshark
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubeshark
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubeshark
    spec:
      serviceAccountName: kubeshark

      containers:
      - name: kubeshark
        image: {{ .Values.image }}:{{ .Values.imageTag }}

        ports:
        - containerPort: 8899

        imagePullPolicy: Always
