apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kubeshark
  name: kubeshark-nodeport
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "http-port"
      port: 8899
      targetPort: 8899
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: kubeshark
